#!/usr/bin/env bash
#configures a new Ubuntu machine
# 1. Install nginx
# 2. Nginx should be listening on port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
# Bash script that configures a new Ubuntu machine and installs ngnx
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart  
