#!/usr/bin/env bash
#configures a new Ubuntu machine
# 1. Install nginx
# 2. Nginx should be listening on port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School

apt-get update
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx restart
