#!/usr/bin/env bash
#configures a new Ubuntu machine
# 1. Install nginx
# 2. Nginx should be listening on port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
#/redirect_me is redirecting to another page.
#“301 Moved Permanently”

apt-get update
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html

new_string="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
file="/etc/nginx/sites-available/default"

sudo sed -i "22i $new_string" $file
service nginx restart
