#!/usr/bin/env bash
#configures a new Ubuntu machine
# 1. Install nginx
# 2. Nginx should be listening on port 80
# 3. When querying Nginx at its root / with a GET request (requesting a page) using curl, it must return a page that contains the string Holberton School
#/redirect_me is redirecting to another page.
#“301 Moved Permanently”
# Create error page 

apt-get update -y
apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html

new_string="\\\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com;\n\t}"
file="/etc/nginx/sites-available/default"
sudo sed -i "22i $new_string" $file

new_string="\\\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
file="/etc/nginx/sites-available/default"
sudo sed -i "22i $new_string" $file

service nginx restart
