#!/usr/bin/env bash
#Bash script that configures an Ubuntu server
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8.
cp /etc/hosts ~/hosts.new
sed -i '/127.*localhost/c\127.0.0.2\tlocalhost' ~/hosts.new
grep -q "8.8.8.8 facebook.com" ~/hosts.new && sed -i '/facebook.com/c\8.8.8.8 facebook.com' ~/hosts.new || echo "8.8.8.8 facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
